baseURL: "https://fransafu.dev"
languageCode: "en-us"
title: "Fransafu.dev"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 4
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-6HQ71MH672

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Fransafu Profile"
  description: It's fransafu's profile
  # staticPath: ""  # The path to serve the static files from
  favicon: "/emoji-fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Fransafu" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Francisco Sánchez"
    subtitle: "Software Engineer"
    content: "A passionate software engineer with a background in computer science that really enjoys create projects where I can apply my knowledge and learn new things. Also, I love sharing my knowledge with others."
    image: /images/photo_4985864411524737877_y.jpg
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/fransafu
        - icon: fab fa-twitter
          url: https://twitter.com/fransafu95
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/fransafu

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/about-me.png"    
    content: |-
      I'm Francisco Sanchez, a Sr. Software Engineer based in Santiago, Chile. With a passion for crafting innovative solutions, I bring 9 years of hands-on experience in software development across diverse sectors, including retail, customer experience, insurance, and healthcare.

      My academic journey has been marked by a Master's in Technology Management and Entrepreneurship, complemented by a Master's in Information Technology. I've also honed my skills through programs such as Babson Build The Entrepreneurship Program, and I hold diplomas in both Artificial Intelligence and Innovation Technology.

      Proficient in Python, Javascript, Typescript and Golang. Also, frontend technologies like React.js and Angular, or backend technologies like Chi (Go), Nest.js, and others frameworks, and database or cloud technologies like PostgreSQL, MySql, Clickhouse, AWS, GCP, and Kubernetes.

      Looking forward to connecting and creating impactful tech solutions together!
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Javascript"
        - "Typescript"
        - "Golang"
        - "Python"
        - "Nest.js"
        - "Express"
        - "React.js"
        - "Angular"
        - "PostgreSQL"
        - "MySQL"
        - "Clickhouse"
        - "AWS"
        - "GCP"
        - "Kubernetes"
        - "Docker"
        - "Git"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: fransafu@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 4
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/fransafu
      linkedin: https://linkedin.com/in/fransafu
      twitter: https://twitter.com/fransafu95

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>